"""Titan-only P11-T contracts and preflight helpers."""

from .contracts import (
    MAIN_TOKEN_SHARES,
    P11_COST_AMENDMENT,
    KimiAPIConfig,
    KimiAPICostLedger,
    KimiAPIResult,
    KimiAPITeacher,
    KimiTrajectory,
    SupervisedTokenRouter,
    build_p11_asset_preflight,
    exact_token_advantage,
    exact_token_opd_loss,
    parse_kimi_structured_trajectory,
    parse_kimi_trajectory,
)
from .cost_calibration import (
    CANDIDATES_PER_DOMAIN,
    DOMAINS,
    REVIEW_COUNT,
    REVIEWS_PER_DOMAIN,
    STAGE_API_BUDGET_CNY,
    deterministic_candidate_pool,
    select_high_information,
    summarize_reviews,
)
from .data import P11_DATA_SEED, stable_id, stable_select
from .probe import (
    KIMI_MAX_REVIEW_ATTEMPTS,
    MAIN_TOKENS,
    P11_5A_AMENDMENT,
    P11_API_TOTAL_HARD_CAP_CNY,
    P11_FP16_INITIAL_LOSS_SCALE,
    P11_FP16_LOSS_SCALE_GROWTH_INTERVAL,
    QWEN_TOKENS,
    RAW_LM_TOKENS,
    accounted_ledger_cost,
    api_call_allowed,
    contract_manifest,
    cumulative_main_quotas,
    equal_trajectory_mean,
    trajectory_mean,
    wave_main_quotas,
)

__all__ = [
    "KimiTrajectory",
    "KimiAPIConfig",
    "KimiAPICostLedger",
    "KimiAPIResult",
    "KimiAPITeacher",
    "MAIN_TOKEN_SHARES",
    "P11_COST_AMENDMENT",
    "SupervisedTokenRouter",
    "build_p11_asset_preflight",
    "exact_token_advantage",
    "exact_token_opd_loss",
    "parse_kimi_trajectory",
    "parse_kimi_structured_trajectory",
    "P11_DATA_SEED",
    "stable_id",
    "stable_select",
    "CANDIDATES_PER_DOMAIN",
    "DOMAINS",
    "REVIEW_COUNT",
    "REVIEWS_PER_DOMAIN",
    "STAGE_API_BUDGET_CNY",
    "deterministic_candidate_pool",
    "select_high_information",
    "summarize_reviews",
    "KIMI_MAX_REVIEW_ATTEMPTS",
    "MAIN_TOKENS",
    "P11_5A_AMENDMENT",
    "P11_API_TOTAL_HARD_CAP_CNY",
    "P11_FP16_INITIAL_LOSS_SCALE",
    "P11_FP16_LOSS_SCALE_GROWTH_INTERVAL",
    "QWEN_TOKENS",
    "RAW_LM_TOKENS",
    "accounted_ledger_cost",
    "api_call_allowed",
    "contract_manifest",
    "cumulative_main_quotas",
    "equal_trajectory_mean",
    "trajectory_mean",
    "wave_main_quotas",
]
